POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4547,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": { "method": "GET", "path": "/api/cars" },
          "deepEquals": { "query": { "brand": "Toyota" } }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": { "Content-Type": "application/json" },
            "body": { "brand": "Toyota", "results": [{ "id": 1, "model": "Corolla", "price": 25000 }, { "id": 2, "model": "Yaris", "price": 18000 }] }
          }
        }
      ]
    }
  ]
}