POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4549,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/login",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "deepEquals": {
            "body": {
              "username": "admin",
              "password": "secret"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "status": "ok",
              "token": "validtoken"
            }
          }
        }
      ]
    }
  ]
}