POST http://localhost:2525/imposters
{
  "port": 4551,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/users",
            "headers": {
              "Content-Type": {
                "contains": "application/json"
              }
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {
              "Content-Type": "application/json",
              "Location": "/api/users/123"
            },
            "body": {
              "id": 123,
              "status": "created",
              "message": "Utilizador criado com sucesso."
            }
          }
        }
      ]
    }
  ]
}